# Generated by Django 2.1.7 on 2020-03-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_sim_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sim_results',
            old_name='First',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='sim_results',
            old_name='Self',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sim_results',
            old_name='Second',
            new_name='second',
        ),
        migrations.RenameField(
            model_name='sim_results',
            old_name='Third',
            new_name='third',
        ),
    ]
